default: &default
  adapter: postgresql
  encoding: unicode
  username: admin
  password: postgres
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: shopify_db

test:
  <<: *default
  database: shopify_test_db
